import {  useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import Articles from '../components/Articles';
import {BASE_URL} from '../utils';
import Footer from '../components/Footer';


export default function Home({articles}) {
  const [food, setFood] = useState(articles.filter(article => article.cat === 'food'));
  const [programming, setProgramming] = useState(articles.filter(article => article.cat === 'programming'));
  const [health, setHealth] = useState(articles.filter(article => article.cat === 'health'));
  const [technology, setTechnology] = useState(articles.filter(article => article.cat === 'technology'));
  const [science, setScience] = useState(articles.filter(article => article.cat === 'science'));


  if(!articles) return <Spiner />
  return (
    <div className="w-full h-full bg-gray-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <div className="mt-10 max-w-[1124px] w-full m-auto">
        <Articles title="programming" articles={programming} bg="#1a1b1f" />
        <Articles title="science"  articles={science} bg="#808080" />
        <Articles title="health"  articles={health} bg="#1a1b1f" />
        <Articles title="technology"  articles={technology} bg="#808080" />
        <Articles title="food"  articles={food} bg="#1a1b1f" />
      </div>
      <Footer />
    </div>
  )
}


export  async function getServerSideProps(){
  const response = await axios.get(`${BASE_URL}/api/posts/posts`);
  const articles = response.data;
  return{
    props: {
      articles
    }  
  }
}
